/***** File generated by ./internal/cmd/ops_generator. Don't edit it directly. *****/

package stablehlo

import (
	"github.com/gomlx/stablehlo/internal/optypes"
)

// Add implements the corresponding standard binary operation.
func (f *Function) Add(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Add, lhs, rhs)
}

// And implements the corresponding standard binary operation.
func (f *Function) And(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.And, lhs, rhs)
}

// Divide implements the corresponding standard binary operation.
func (f *Function) Divide(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Divide, lhs, rhs)
}

// Maximum implements the corresponding standard binary operation.
func (f *Function) Maximum(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Maximum, lhs, rhs)
}

// Minimum implements the corresponding standard binary operation.
func (f *Function) Minimum(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Minimum, lhs, rhs)
}

// Multiply implements the corresponding standard binary operation.
func (f *Function) Multiply(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Multiply, lhs, rhs)
}

// Or implements the corresponding standard binary operation.
func (f *Function) Or(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Or, lhs, rhs)
}

// Power implements the corresponding standard binary operation.
func (f *Function) Power(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Power, lhs, rhs)
}

// Remainder implements the corresponding standard binary operation.
func (f *Function) Remainder(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Remainder, lhs, rhs)
}

// Subtract implements the corresponding standard binary operation.
func (f *Function) Subtract(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Subtract, lhs, rhs)
}

// Xor implements the corresponding standard binary operation.
func (f *Function) Xor(lhs, rhs *Value) (*Value, error) {
	return f.binaryOp(optypes.Xor, lhs, rhs)
}
